GMX_PREFIX = '/usr/local/gromacs/bin/gmx' # potoff
#GMX_PREFIX = 'gmx' # grid

NAME_EQ_NVT = 'EQ_NVT'
NAME_EQ_SURFTEN = 'EQ_SURFTEN'; NAME_PRO_SURFTEN = 'PRO_SURFTEN'

NAME_ELONGATED = 'ELONGATED_BOX_PLACEHOLDER'

NAME_EQ_CHUNK_COUNT = int(10)
NAME_PRO_CHUNK_COUNT = int(4)

# chunked

EQ_SURFTEN_CHUNK_TO_STARTING_GRO_FILE = {
    0 : f'{NAME_ELONGATED}',
    1 : f'{NAME_EQ_SURFTEN}_CHUNK_1',
    2 : f'{NAME_EQ_SURFTEN}_CHUNK_2',
    3 : f'{NAME_EQ_SURFTEN}_CHUNK_3',
    4 : f'{NAME_EQ_SURFTEN}_CHUNK_4',
    5 : f'{NAME_EQ_SURFTEN}_CHUNK_5',
    6 : f'{NAME_EQ_SURFTEN}_CHUNK_6',
    7 : f'{NAME_EQ_SURFTEN}_CHUNK_7',
    8 : f'{NAME_EQ_SURFTEN}_CHUNK_8',
    9 : f'{NAME_EQ_SURFTEN}_CHUNK_9'
}

PRO_SURFTEN_CHUNK_TO_STARTING_GRO_FILE = {
    0 : f'{NAME_EQ_SURFTEN}_CHUNK_9',
    1 : f'{NAME_PRO_SURFTEN}_CHUNK_1',
    2 : f'{NAME_PRO_SURFTEN}_CHUNK_2',
    3 : f'{NAME_PRO_SURFTEN}_CHUNK_3'
}









